Reportes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("sales/", include("sales.urls")),
]

sales/urls.py
from django.urls import path

from sales.views import SalesList, SaleDetailView

urlpatterns = [
    path("", SalesList.as_view(), name="sales"),
    path("<int:pk>/", SaleDetailView.as_view(), name="sale_detail"),

]

products/models.py
from django.db import models


class Product(models.Model):
    id = models.AutoField(db_column='Id', primary_key=True)
    producttypeid = models.ForeignKey('Producttype', models.DO_NOTHING, db_column='ProductTypeId')
    productname = models.CharField(db_column='ProductName', max_length=500)
    code = models.IntegerField(db_column='Code')
    cost = models.TextField(db_column='Cost')
    price = models.TextField(db_column='Price')
    wholesale = models.TextField(db_column='Wholesale')
    unitid = models.ForeignKey('Unit', models.DO_NOTHING, db_column='UnitId')
    profitpercentage = models.TextField(db_column='ProfitPercentage')
    applypercentage = models.TextField(db_column='ApplyPercentage')
    existence = models.TextField(db_column='Existence')
    userid = models.IntegerField(db_column='UserId')
    creationdate = models.DateTimeField(db_column='CreationDate')
    updatedate = models.DateTimeField(db_column='UpdateDate')
    active = models.TextField(db_column='Active')

    class Meta:
        managed = False
        db_table = 'Product'


class Producttype(models.Model):
    id = models.AutoField(db_column='Id', primary_key=True)
    producttypename = models.CharField(db_column='ProductTypeName', max_length=50)
    userid = models.IntegerField(db_column='UserId')
    creationdate = models.DateTimeField(db_column='CreationDate')
    updatedate = models.DateTimeField(db_column='UpdateDate')
    active = models.TextField(db_column='Active')

    class Meta:
        managed = False
        db_table = 'ProductType'


class Unit(models.Model):
    id = models.AutoField(db_column='Id', primary_key=True)  # Field name made lowercase.
    unitname = models.CharField(db_column='UnitName', max_length=50)  # Field name made lowercase.
    unitcode = models.CharField(db_column='UnitCode', max_length=50)  # Field name made lowercase.
    creationdate = models.DateTimeField(db_column='CreationDate')  # Field name made lowercase.
    updatedate = models.DateTimeField(db_column='UpdateDate')  # Field name made lowercase.
    active = models.TextField(db_column='Active')  # Field name made lowercase. This field type is a guess.

    class Meta:
        managed = False
        db_table = 'Unit'

sales/models.py
from django.db import models

from products.models import Product, Unit


class Sale(models.Model):
    id = models.AutoField(db_column='Id', primary_key=True)
    salename = models.TextField(db_column='SaleName')
    total = models.FloatField(db_column='Total')
    paycash = models.BooleanField(db_column='PayCash')
    paywith = models.FloatField(db_column='PayWith')
    wholesale = models.BooleanField(db_column='Wholesale')
    completed = models.BooleanField(db_column='Completed')
    # userid = models.ForeignKey('User', models.DO_NOTHING, db_column='UserId')
    creationdate = models.DateTimeField(db_column='CreationDate', auto_now_add=True, blank=True, null=True)
    updatedate = models.DateTimeField(db_column='UpdateDate', auto_now=True, blank=True, null=True)
    active = models.BooleanField(db_column='Active')

    class Meta:
        managed = False
        db_table = 'Sale'


class Saledetail(models.Model):
    id = models.AutoField(db_column='Id', primary_key=True)
    saleid = models.ForeignKey(Sale, models.DO_NOTHING, db_column='SaleId')
    productid = models.ForeignKey(Product, models.DO_NOTHING, db_column='ProductId')
    cost = models.TextField(db_column='Cost')
    price = models.TextField(db_column='Price')
    wholesale = models.TextField(db_column='WholeSale')
    quantity = models.TextField(db_column='Quantity')
    amount = models.TextField(db_column='Amount')
    unitid = models.ForeignKey(Unit, models.DO_NOTHING, db_column='UnitId')
    promotiondescription = models.CharField(db_column='PromotionDescription', max_length=500)
    markedasrefund = models.TextField(db_column='MarkedAsRefund')
    refund = models.TextField(db_column='Refund')
    ispromotion = models.TextField(db_column='IsPromotion')
    iswholesale = models.TextField(db_column='IsWholeSale')
    creationdate = models.DateTimeField(db_column='CreationDate')
    updatedate = models.DateTimeField(db_column='UpdateDate')
    active = models.TextField(db_column='Active')

    class Meta:
        managed = False
        db_table = 'SaleDetail'

products/views.py
from django.shortcuts import render

# Create your views here.

sales/views.py
from django.shortcuts import render
from django.views.generic import DetailView
from rest_framework import generics
from .models import Sale
from .serializers import SalesSerializer

class SalesList(generics.ListAPIView):
    serializer_class = SalesSerializer
    queryset = Sale.objects.all().order_by("-id")

    def get(self, request, *args, **kwargs):
        start_date = request.query_params.get('start_date', None)
        end_date = request.query_params.get('end_date', None)
        if start_date and end_date:
            self.queryset = self.queryset.filter(date__range=[start_date, end_date])
        return render(request, 'sales_list.html', {'sales':
                                                       self.get_queryset()})


class SaleDetailView(DetailView):
    model = Sale
    template_name = 'sale_detail.html'
    context_object_name = 'sale'

templates/sale_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detalle de Venta</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }
        .container {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            color: #333;
            text-align: center;
            margin-bottom: 20px;
        }
        .detail-item {
            margin-bottom: 10px;
        }
        .detail-item strong {
            font-weight: bold;
            margin-right: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Detalle de Venta</h1>
        <div class="detail-item">
            <strong>Ticket #:</strong> {{ sale.id }}
        </div>
        <div class="detail-item">
            <strong>Total:</strong> {{ sale.total|floatformat:"2" }}
        </div>
        <div class="detail-item">
            <strong>Metodo de pago:</strong>
            {% if sale.paycash == 1 %} Efectivo {% else %} Tarjeta/Transferencia {% endif %}
        </div>
        <div class="detail-item">
            <strong>Fecha:</strong> {{ sale.updatedate|date:"d-m-Y H:i:s" }}
        </div>
        <h2>Productos en la venta:</h2>
        <table>
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Monto Unitario</th>
                    <th>Cantidad</th>
                    <th>Unidad</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                {% for item in sale.saledetail_set.all %}
                <tr>
                    <td>{{ item.productid.productname }}</td>
                    <td>{{ item.price|floatformat:"2" }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>{{ item.productid.unitid.unitname }}</td>
                    <td>{{ item.amount|floatformat:"2" }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>

templates/sales_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List of Sales</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }
        .container {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1, h2 {
            text-align: center;
        }
        form {
            text-align: center;
            margin-bottom: 20px;
        }
        form label {
            margin-right: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        td a {
            color: #007bff;
            text-decoration: none;
        }
        td a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Lista de ventas</h1>
        <form method="GET">
            <label for="start_date">Fecha de inicio:</label>
            <input type="date" id="start_date" name="start_date">
            <label for="end_date">Fecha de fin:</label>
            <input type="date" id="end_date" name="end_date">
            <button type="submit">Filter</button>
        </form>
        <table>
            <thead>
                <tr>
                    <th>Ticket #</th>
                    <th>Total</th>
                    <th>Metodo de pago</th>
                    <th>Fecha</th>
                </tr>
            </thead>
            <tbody>
                {% for sale in sales %}
                <tr>
                    <td><a href="{% url 'sale_detail' sale.id %}">{{ sale.id }}</a></td>
                    <td>{{ sale.total|floatformat:"2" }}</td>
                    <td>{% if sale.paycash == 1 %} Efectivo {% else %} Tarjeta/Transferencia {% endif %}</td>
                    <td>{{ sale.updatedate|date:"d-m-Y H:i:s" }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>